### PR TITLE
Spanish language update in Cracker's Wither Storm Mod

### PR DESCRIPTION
**Pull request by TheSrBig**
Hello nonamecrackers2,

I hope you are well. I am writing to inform you that I have done a complete update of all the Spanish texts in Cracker's Wither Storm Mod.

As a native speaker of Mexican Spanish, I have carefully reviewed all the texts and corrected any translation errors I found. In addition, I have updated the languages to the latest version of the mod (A Block and a Hard Place) to make sure that everything is up to date and consistent in all available versions of the game.

I am pleased to inform you that I have completed the update in all the languages available in the game and in the mod. Now, Spanish-speaking players will be able to enjoy a smoother game experience without translation errors.

As a native Mexican Spanish speaker, I hope this update will be useful for you and your users. If you have any questions or comments about my work, please don't hesitate to contact me.

Thank you for your time and I look forward to hearing from you soon.

Sincerely yours,
Diego García Rojo
[lang.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10833090/lang.zip)

### CODE REVIEW

**Comment by TheSrBig** [comment]
[lang.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10833088/lang.zip)

**Comment by TheSrBig** [comment]
one thing I have seen is that in the Spanish translation files, there are no such descriptions for the configurations.
image
image

**Comment by myron-obsolete-account** [comment]
The config descriptions cannot be changes via language files, don't worry it's fine.

**Comment by nonamecrackers2** [comment]
Yeah, config descs can't be translated

**Comment by TheSrBig** [comment]
> Yeah, config descs can't be translated

So it will be added?

**Comment by nonamecrackers2** [comment]
Still needs to be reviewed, patience

**Comment by NinjaSam5399** [comment]
You could use google translate if you do not understand.

**Comment by nonamecrackers2** [comment]
Will be added in the upcoming 1.19.4 update

**Comment by TheSrBig** [comment]
Perfect

**Pull request closed without merging**
