### PR TITLE
added a quarter of translation

### PR DESCRIPTION
**Pull request by ApfelTeeSaft**
im gonna add more tomorrow

### CODE REVIEW

**Comment by Loverxzc** [comment]
tomorrow... 10 days ago

**Comment by ApfelTeeSaft** [comment]
Sorry I’ve been really busy because of school :/ but I can start again in
like 5 days

Loverxzc ***@***.***> schrieb am Do. 4. Aug. 2022 um 21:37:

**Comment by nonamecrackers2** [comment]
Setting as draft until fully completed

**Comment by nonamecrackers2** [comment]
Closing until fully completed

**Pull request closed without merging**
