### PR TITLE
Updated/Adapted 1.19.4 pt_br.json

### PR DESCRIPTION
**Pull request by chocotoneg**
As a brazillian portuguese speaker, i made some corrections and adaptions to the pt_br.json lang.

### CODE REVIEW

**Review by nonamecrackers2 — COMMENTED** [review]
All looks good!

**Review by nonamecrackers2 — COMMENTED** [review]
All looks good!

**Review by nonamecrackers2 — APPROVED** [review]
All looks good! (Sorry for the duplicate comments, was trying to get the review to work)

**Comment by Luisinhi010** [comment]
boa mano, valeu por melhorar a tradução

**Pull request merged**
