### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by Gilese86a-github**
Changed some translations and added translations for advancements, items, and descriptions.

### CODE REVIEW

**Comment by Gilese86a-github** [comment]
[zh_cn.json](https://github.com/user-attachments/files/16782426/zh_cn.json)

**Comment by Gilese86a-github** [comment]
> 文件：

**Comment by Gilese86a-github** [comment]
> 文件：

**Comment by Gilese86a-github** [comment]
File:
[zh_cn.json](https://github.com/user-attachments/files/16914451/zh_cn.json)
This change also matches my second change to zh_cn.json (please choose this change, the previous translation seems to have not taken effect)
Fixed zh_cn.json 9-7 utc8:00

**Comment by watersofnazareth** [comment]
Completed

**Pull request closed without merging**
