### PR TITLE
Create Omari white

### PR DESCRIPTION
**Pull request by Omariwhite**

### CODE REVIEW

**Comment by Omariwhite** [comment]
Crackers wither storm

**Comment by myron-obsolete-account** [comment]
what?

**Comment by NinjaSam5399** [comment]
uhhhh

**Comment by myron-obsolete-account** [comment]
hi @Omariwhite what was the purpose of this...?

**Comment by myron-obsolete-account** [comment]
just curious

**Comment by NinjaSam5399** [comment]
Mark this as Invalid please.

**Pull request closed without merging**
