### PR TITLE
Translation for all Spanish languages ​​for the mod

### PR DESCRIPTION
**Pull request by pox1016**
[es_ec.json.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9312349/es_ec.json.txt)
[es_es.json.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9312350/es_es.json.txt)
[es_mx.json.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9312351/es_mx.json.txt)
[es_uy.json.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9312352/es_uy.json.txt)
[es_ve.json.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9312353/es_ve.json.txt)
[es_ar.json.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9312354/es_ar.json.txt)
[es_cl.json.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9312355/es_cl.json.txt)

### CODE REVIEW

**Comment by nonamecrackers2** [comment]
I feel only the es_es should be translated instead of copying the translation to all the other variants of Spanish. I'm not a Spanish speaker but I feel there would be differences between each version of Spanish.

**Comment by pox1016** [comment]
> I feel only the es_es should be translated instead of copying the translation to all the other variants of Spanish. I'm not a Spanish speaker but I feel there would be differences between each version of Spanish.

In fact I planned to give an exclusive touch to each Spanish variant in the future but for now I think this will be very useful and will be a first step in the translation into Spanish, but I do consider it very necessary to add all the variants even if they are all the same so that at least they are will be more or less translated for all Spanish-speaking users, btw the variant that I have translated is that of es_es (Spain).

**Comment by nonamecrackers2** [comment]
> In fact I planned to give an exclusive touch to each Spanish variant in the future but for now I think this will be very useful and will be a first step in the translation into Spanish, but I do consider it very necessary to add all the variants even if they are all the same so that at least they are will be more or less translated for all Spanish-speaking users, btw the variant that I have translated is that of es_es (Spain).

Alright, as long as if you plan on working on each variation

**Comment by pox1016** [comment]
> Alright, as long as if you plan on working on each variation

I promise you I will do it, by the way, there is nothing missing to translate right?, because I saw that the lang is different between the version of the mod for 1.16.5 and for the other 2, I think it is because the version of 1.16.5 is outdated (without the amulet) (I used the lang from 1.16.5).

**Comment by nonamecrackers2** [comment]
Yeah you'd need to translate the 1.18.2 version as well.

**Comment by pox1016** [comment]
Translation of the mod for Spanish for version **1.18.2** (no word variations between Spanish variants, this will be included very soon, the first variant that will be ready will be for **Spanish Argentina** and I will release the translation in a few weeks):
[es_ar.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9540892/es_ar.txt)
[es_cl.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9540893/es_cl.txt)
[es_ec.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9540895/es_ec.txt)
[es_es.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9540896/es_es.txt)
[es_mx.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9540897/es_mx.txt)
[es_uy.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9540898/es_uy.txt)
[es_ve.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9540899/es_ve.txt)

Sorry for the delay! I was a bit busy :(

**Comment by nonamecrackers2** [comment]
No worries!

**Comment by nonamecrackers2** [comment]
Now implemented in all versions

**Comment by pox1016** [comment]
Spanish translation update:

[es_ar.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10332813/es_ar.txt)
[es_cl.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10332815/es_cl.txt)
[es_ec.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10332816/es_ec.txt)
[es_es.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10332817/es_es.txt)
[es_mx.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10332819/es_mx.txt)
[es_ve.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10332821/es_ve.txt)
[es_uy.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10332820/es_uy.txt)

**Pull request closed without merging**
